### ISSUE TITLE
특정 호스트 이름을 가진 서버를 찾을수 없습니다라고 떠요ㅠ

### ISSUE THREAD

**Issue by cococow23** [0jae0/auto-hcs-shortcut#1]
![B4DF97B1-660D-4047-863C-4142463FE674](https://user-images.githubusercontent.com/113398096/209484117-e1abcb7d-aeee-47d7-99aa-9efeefee8b6e.png)

어떻게 된걸까요ㅠ

**Comment by 0jae0** [comment]
도메인이 아이클라우드 릴레이에 들어가면서 DNS 설정이 바뀌어 그렇습니다.. 현재 고치긴 했는데 아직 안될까요??

2022년 12월 26일 (월) 오전 8:07, cococow23 ***@***.***>님이 작성:

**Comment by cococow23** [comment]
엇 이제 됩니다!! 감사합니다 🥰
